### ISSUE TITLE
1.1.1.Final maven release

### ISSUE THREAD

**Issue by ismailsimsek** [jboss-logging/log4j2-jboss-logmanager#32]
1.1.1.Final version is not available in maven is it published to maven ?

https://mvnrepository.com/artifact/org.jboss.logmanager/log4j2-jboss-logmanager

**Comment by jamezp** [comment]
Hi @ismailsimsek Sorry, there has been an issue with syncing JBoss Nexus to Maven Central. It's available here https://repository.jboss.org/nexus/content/groups/public/org/jboss/logmanager/log4j2-jboss-logmanager/1.1.1.Final/.

If you want to add the repository you can add the following to your pom:
```xml
<repositories>
    <repository>
        <id>jboss-public-repository-group</id>
        <name>JBoss Public Repository Group</name>
        <url>https://repository.jboss.org/nexus/content/groups/public/</url>
        <layout>default</layout>
        <releases>
            <enabled>true</enabled>
            <updatePolicy>never</updatePolicy>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
</repositories>
```

Please note too not much has changed other than the increased priority for the provider and the upgrade of the log4j-api. The intent of this release mainly to stop security scanners from false positivies.
