### ISSUE TITLE
log4j 1.2 vs log4j 2 default level mapping

### ISSUE THREAD

**Issue by boris-unckel** [jboss-logging/log4j2-jboss-logmanager#5]
In https://github.com/jboss-logging/log4j-jboss-logmanager/blob/master/src/main/java/org/apache/log4j/JBossLevelMapping.java the default level is DEBUG.
In https://github.com/jboss-logging/log4j2-jboss-logmanager/blob/master/src/main/java/org/jboss/logmanager/log4j/LevelTranslator.java the default level is INFO.

I don't have a preference, but I think both should act same.

**Comment by jamezp** [comment]
Took me a minute to find it, but it does look like it should be DEBUG. That appears to be the default for log4j2 as well. Thanks for finding this!
