### ISSUE TITLE
add logic similar to how log4j2 handle filters

### ISSUE THREAD

**Issue by cuichenli** [jboss-logging/log4j2-jboss-logmanager#65]
The Logger class in log4j2 contains a built-in feature that applies filters before evaluating the log level. This functionality can be useful to users. You can find an example of this implementation on GitHub at: https://github.com/apache/logging-log4j2/blob/2.x/log4j-core/src/main/java/org/apache/logging/log4j/core/Logger.java#L177 . In the filter function, if the filter returns a positive result, the message will be logged.

Any chance we can add the similar logic in this library? Thanks!

**Comment by dmlloyd** [comment]
In the JBoss LogManager, it was a deliberate design choice to test the level before applying filters. Any nontrivial logic before this point can have significant and detrimental performance impact, since many libraries and systems are known to make extensive use of debug and trace logging.

**Comment by cuichenli** [comment]
got it, thanks!
